article_homepage:
    path:     /
    defaults: { _controller: ArticleBundle:Default:index }

article_detail:
    path:     /article/detail/{slug}-{id}
    defaults: { _controller: ArticleBundle:Default:detail }
    requirements:
        id: \d+
        slug: "[a-zA-Z0-9-]+"

article_list:
    path:     /article/liste
    defaults: {_controller: ArticleBundle:Default:list}

article_add:
    path:     /article/ajouter
    defaults: {_controller: ArticleBundle:Default:add}

article_delete:
    path:     /article/supprimer/{id}
    defaults: {_controller: ArticleBundle:Default:delete}
    requirements:
        id: \d+

article_update:
    path:     /article/editer/{id}
    defaults: {_controller: ArticleBundle:Default:update}
    methods:  [GET]
    requirements:
        id: \d+

article_update_post:
    path:     /article/editer-via-post/{id}
    defaults: {_controller: ArticleBundle:Default:updatePost}
    methods:  [POST]
    requirements:
        id: \d+

article_add_image:
    path:     /article/{id}/add-image
    defaults: {_controller: ArticleBundle:Default:addImage}
    requirements:
        id: \d+

test_hello:
    path:  /test/hello
    defaults: {_controller: ArticleBundle:Test:hello}


