<?php

namespace ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findAllWithComments()
    {
        $qb = $this->createQueryBuilder("art");
        $qb->leftJoin("art.comments", "comments_alias");
        $qb->addSelect("comments_alias");
        $qb->orderBy("art.updatedAt");

        return $qb->getQuery()->getResult();
    }

    public function findArticleByDescription($description)
    {
        $qb = $this->createQueryBuilder("art");
        $qb
            ->orderBy("art.createdAt", "DESC")
            ->where("art.description LIKE :description")
            ->setParameter(":description", "%$description%");

        return $qb
            ->getQuery()
            ->getResult();
    }

}
